### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by Laeborg** [richibrics/HassMonitorMqtt#4]
I get this error when validating my configuration through Git Pull (https://github.com/home-assistant/addons/tree/master/git_pull)
```
Failed config
  General Errors: 
    - Component error: monitor_mqtt - cannot import name 'ATTR_DISCOVERY_HASH' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)
```

**Comment by richibrics** [comment]
That’s strange, could you tell me which version of HomeAssistant are you
using ?

**Comment by Laeborg** [comment]
Of course.

Home Assistant OS 5.10
Core: core-2021.1.4
SuperVisor: supervisor-2021.01.5

The monitor seems to be working, but throws the validation error so my system can't auto restart on changes.

**Comment by richibrics** [comment]
HomeAssistant is updating due to some security issues so something could be have changed. Could you try the new feature of PyMonitorMqtt that makes all sensors and switches appear in HomeAssistant automatically please ? You can find the configuration file link in the README (rename the file to configuration.yaml). With that system you don't need anymore this integration (I need someone to test it).
Thank you, let me know

**Comment by Laeborg** [comment]
That seems to be working.
Thank you :)

**Comment by richibrics** [comment]
Perfect.
For every problem, please open an issue (on the PyMonitor repo) because each report is essential to continue to improve the program.
